package com.app.SalesInventory;

import android.content.Context;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.element.Text;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;

import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

public class PDFGenerator {

    private Context context;
    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault());
    private PdfFont boldFont;
    private PdfFont regularFont;

    public PDFGenerator(Context context) throws Exception {
        this.context = context;
        // Create fonts
        this.boldFont = PdfFontFactory.createFont();
        this.regularFont = PdfFontFactory.createFont();
    }

    /**
     * Generate Stock Value Report PDF
     */
    public void generateStockValueReportPDF(File outputFile, List<StockValueReport> reports) throws Exception {
        PdfWriter writer = new PdfWriter(new FileOutputStream(outputFile));
        PdfDocument pdfDoc = new PdfDocument(writer);
        Document document = new Document(pdfDoc);

        // Title
        Text titleText = new Text("STOCK VALUE REPORT");
        Paragraph title = new Paragraph(titleText)
                .setFont(boldFont)
                .setFontSize(20)
                .setTextAlignment(TextAlignment.CENTER);
        document.add(title);

        // Date generated
        Paragraph dateGen = new Paragraph("Generated on: " + dateFormat.format(new Date()))
                .setFontSize(10)
                .setTextAlignment(TextAlignment.CENTER);
        document.add(dateGen);

        // Summary section
        Text summaryText = new Text("SUMMARY");
        Paragraph summaryTitle = new Paragraph(summaryText)
                .setFont(boldFont)
                .setFontSize(14);
        document.add(summaryTitle);

        double totalCostValue = 0;
        double totalSellingValue = 0;
        double totalProfit = 0;

        for (StockValueReport report : reports) {
            totalCostValue += report.getTotalCostValue();
            totalSellingValue += report.getTotalSellingValue();
            totalProfit += report.getProfit();
        }

        document.add(new Paragraph(String.format("Total Cost Value: ₱%.2f", totalCostValue)));
        document.add(new Paragraph(String.format("Total Selling Value: ₱%.2f", totalSellingValue)));
        document.add(new Paragraph(String.format("Total Profit: ₱%.2f", totalProfit)));
        document.add(new Paragraph(String.format("Overall Margin: %.2f%%",
                totalSellingValue > 0 ? (totalProfit / totalSellingValue) * 100 : 0)));

        // Details table
        Text detailsText = new Text("DETAILED REPORT");
        Paragraph detailsTitle = new Paragraph(detailsText)
                .setFont(boldFont)
                .setFontSize(14)
                .setMarginTop(10);
        document.add(detailsTitle);

        Table table = new Table(UnitValue.createPercentArray(new float[]{2, 1.5f, 1, 1.2f, 1.2f, 1, 0.8f}));
        table.setWidth(UnitValue.createPercentValue(100));

        // Header row
        table.addHeaderCell(createHeaderCell("Product Name"));
        table.addHeaderCell(createHeaderCell("Category"));
        table.addHeaderCell(createHeaderCell("Qty"));
        table.addHeaderCell(createHeaderCell("Cost Value"));
        table.addHeaderCell(createHeaderCell("Selling Value"));
        table.addHeaderCell(createHeaderCell("Profit"));
        table.addHeaderCell(createHeaderCell("Margin"));

        // Data rows
        for (StockValueReport report : reports) {
            table.addCell(report.getProductName());
            table.addCell(report.getCategory());
            table.addCell(String.valueOf(report.getQuantity()));
            table.addCell(String.format("₱%.2f", report.getTotalCostValue()));
            table.addCell(String.format("₱%.2f", report.getTotalSellingValue()));
            table.addCell(String.format("₱%.2f", report.getProfit()));
            table.addCell(report.getProfitMargin());
        }

        document.add(table);

        // Footer
        document.add(new Paragraph("\n\nReport generated by: Sales Inventory System")
                .setFontSize(9)
                .setTextAlignment(TextAlignment.CENTER));

        document.close();
    }

    /**
     * Generate Stock Movement Report PDF
     */
    public void generateStockMovementReportPDF(File outputFile, List<StockMovementReport> reports,
                                               int totalReceived, int totalSold, int totalAdjustments) throws Exception {
        PdfWriter writer = new PdfWriter(new FileOutputStream(outputFile));
        PdfDocument pdfDoc = new PdfDocument(writer);
        Document document = new Document(pdfDoc);

        // Title
        Text titleText = new Text("STOCK MOVEMENT REPORT");
        Paragraph title = new Paragraph(titleText)
                .setFont(boldFont)
                .setFontSize(20)
                .setTextAlignment(TextAlignment.CENTER);
        document.add(title);

        // Date generated
        Paragraph dateGen = new Paragraph("Generated on: " + dateFormat.format(new Date()))
                .setFontSize(10)
                .setTextAlignment(TextAlignment.CENTER);
        document.add(dateGen);

        // Summary section
        Text summaryText = new Text("SUMMARY");
        Paragraph summaryTitle = new Paragraph(summaryText)
                .setFont(boldFont)
                .setFontSize(14);
        document.add(summaryTitle);

        document.add(new Paragraph("Total Received: " + totalReceived + " units"));
        document.add(new Paragraph("Total Sold: " + totalSold + " units"));
        document.add(new Paragraph("Total Adjustments: " + totalAdjustments + " units"));

        // Details table
        Text detailsText = new Text("DETAILED REPORT");
        Paragraph detailsTitle = new Paragraph(detailsText)
                .setFont(boldFont)
                .setFontSize(14)
                .setMarginTop(10);
        document.add(detailsTitle);

        Table table = new Table(UnitValue.createPercentArray(new float[]{1.5f, 1.2f, 0.8f, 0.8f, 0.8f, 0.8f, 0.8f, 0.8f}));
        table.setWidth(UnitValue.createPercentValue(100));

        // Header row
        table.addHeaderCell(createHeaderCell("Product"));
        table.addHeaderCell(createHeaderCell("Category"));
        table.addHeaderCell(createHeaderCell("Opening"));
        table.addHeaderCell(createHeaderCell("Received"));
        table.addHeaderCell(createHeaderCell("Sold"));
        table.addHeaderCell(createHeaderCell("Adjusted"));
        table.addHeaderCell(createHeaderCell("Closing"));
        table.addHeaderCell(createHeaderCell("Movement %"));

        // Data rows
        for (StockMovementReport report : reports) {
            table.addCell(report.getProductName());
            table.addCell(report.getCategory());
            table.addCell(String.valueOf(report.getOpeningStock()));
            table.addCell(String.valueOf(report.getReceived()));
            table.addCell(String.valueOf(report.getSold()));
            table.addCell(String.valueOf(report.getAdjusted()));
            table.addCell(String.valueOf(report.getClosingStock()));
            table.addCell(String.format("%.2f%%", report.getMovementPercentage()));
        }

        document.add(table);

        // Footer
        document.add(new Paragraph("\n\nReport generated by: Sales Inventory System")
                .setFontSize(9)
                .setTextAlignment(TextAlignment.CENTER));

        document.close();
    }

    /**
     * Generate Adjustment Summary Report PDF
     */
    public void generateAdjustmentSummaryReportPDF(File outputFile, List<AdjustmentSummaryData> summaryList,
                                                   int totalAdjustments, int totalAdditions, int totalRemovals) throws Exception {
        PdfWriter writer = new PdfWriter(new FileOutputStream(outputFile));
        PdfDocument pdfDoc = new PdfDocument(writer);
        Document document = new Document(pdfDoc);

        // Title
        Text titleText = new Text("ADJUSTMENT SUMMARY REPORT");
        Paragraph title = new Paragraph(titleText)
                .setFont(boldFont)
                .setFontSize(20)
                .setTextAlignment(TextAlignment.CENTER);
        document.add(title);

        // Date generated
        Paragraph dateGen = new Paragraph("Generated on: " + dateFormat.format(new Date()))
                .setFontSize(10)
                .setTextAlignment(TextAlignment.CENTER);
        document.add(dateGen);

        // Summary section
        Text summaryText = new Text("SUMMARY");
        Paragraph summaryTitle = new Paragraph(summaryText)
                .setFont(boldFont)
                .setFontSize(14);
        document.add(summaryTitle);

        document.add(new Paragraph("Total Adjustments: " + totalAdjustments));
        document.add(new Paragraph("Total Units Added: +" + totalAdditions));
        document.add(new Paragraph("Total Units Removed: -" + totalRemovals));
        document.add(new Paragraph("Net Change: " + (totalAdditions - totalRemovals)));

        // Details table
        Text detailsText = new Text("DETAILED REPORT");
        Paragraph detailsTitle = new Paragraph(detailsText)
                .setFont(boldFont)
                .setFontSize(14)
                .setMarginTop(10);
        document.add(detailsTitle);

        Table table = new Table(UnitValue.createPercentArray(new float[]{2, 1, 1, 1, 1, 2}));
        table.setWidth(UnitValue.createPercentValue(100));

        // Header row
        table.addHeaderCell(createHeaderCell("Product"));
        table.addHeaderCell(createHeaderCell("Total Adj"));
        table.addHeaderCell(createHeaderCell("Added"));
        table.addHeaderCell(createHeaderCell("Removed"));
        table.addHeaderCell(createHeaderCell("Net Change"));
        table.addHeaderCell(createHeaderCell("Reasons"));

        // Data rows
        for (AdjustmentSummaryData summary : summaryList) {
            table.addCell(summary.getProductName());
            table.addCell(String.valueOf(summary.getTotalAdjustments()));
            table.addCell("+" + summary.getTotalAdditions());
            table.addCell("-" + summary.getTotalRemovals());
            table.addCell(String.valueOf(summary.getNetChange()));

            StringBuilder reasons = new StringBuilder();
            if (!summary.getAdditionReasons().isEmpty()) {
                reasons.append("Added: ").append(String.join(", ", summary.getAdditionReasons()));
            }
            if (!summary.getRemovalReasons().isEmpty()) {
                if (reasons.length() > 0) reasons.append("; ");
                reasons.append("Removed: ").append(String.join(", ", summary.getRemovalReasons()));
            }
            table.addCell(reasons.toString());
        }

        document.add(table);

        // Footer
        document.add(new Paragraph("\n\nReport generated by: Sales Inventory System")
                .setFontSize(9)
                .setTextAlignment(TextAlignment.CENTER));

        document.close();
    }

    /**
     * Create header cell for PDF table with bold text
     */
    private Cell createHeaderCell(String text) throws Exception {
        Text headerText = new Text(text);
        Paragraph headerParagraph = new Paragraph(headerText)
                .setFont(boldFont);

        return new Cell()
                .add(headerParagraph)
                .setTextAlignment(TextAlignment.CENTER)
                .setBackgroundColor(com.itextpdf.kernel.colors.ColorConstants.LIGHT_GRAY);
    }
}