package com.app.SalesInventory;

import android.content.Context;
import android.os.Environment;
import android.widget.Toast;
import android.net.Uri;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class ReportExportUtil {

    public static final int EXPORT_PDF = 1;

    private Context context;
    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd_HH-mm-ss", Locale.getDefault());

    public static class ExportResult {
        public OutputStream outputStream;
        public Uri uri;
        public String displayPath;
        public File file;
    }

    public ReportExportUtil(Context context) {
        this.context = context;
    }

    public boolean isStorageAvailable() {
        String state = Environment.getExternalStorageState();
        return Environment.MEDIA_MOUNTED.equals(state);
    }

    public File getExportDirectory() {
        File base = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS);
        if (base == null) base = context.getFilesDir();
        File directory = new File(base, "SalesInventory_Reports");
        if (!directory.exists()) {
            directory.mkdirs();
        }
        return directory;
    }

    public String generateFileName(String prefix) {
        return prefix + "_" + dateFormat.format(new Date()) + ".pdf";
    }

    public String generateFileName(String prefix, int exportType) {
        return generateFileName(prefix);
    }

    public ExportResult createOutputStreamForFile(String fileName, int exportType) throws Exception {
        return createOutputStreamForFile(fileName);
    }

    public ExportResult createOutputStreamForFile(String fileName) throws Exception {
        if (!isStorageAvailable()) {
            throw new Exception("External storage is not available or not writable.");
        }

        File directory = getExportDirectory();
        File file = new File(directory, fileName);
        FileOutputStream fos = new FileOutputStream(file);

        ExportResult result = new ExportResult();
        result.outputStream = fos;
        result.file = file;
        result.displayPath = file.getAbsolutePath();

        try {
            result.uri = androidx.core.content.FileProvider.getUriForFile(
                    context, context.getPackageName() + ".provider", file);
        } catch (Exception e) {
            e.printStackTrace();
        }

        return result;
    }

    public void showExportSuccess(String path) {
        Toast.makeText(context, "Export Successful!\nSaved to: " + path, Toast.LENGTH_LONG).show();
    }

    public void showExportError(String error) {
        Toast.makeText(context, "Export Failed: " + error, Toast.LENGTH_LONG).show();
    }

    public void shareFileViaEmail(File file, String subject) {
        try {
            Uri fileUri = androidx.core.content.FileProvider.getUriForFile(
                    context, context.getPackageName() + ".provider", file);

            android.content.Intent emailIntent = new android.content.Intent(android.content.Intent.ACTION_SEND);
            emailIntent.setType("application/pdf");
            emailIntent.putExtra(android.content.Intent.EXTRA_SUBJECT, subject);

            // --- CRITICAL FIX 1: Fetch User Info for the Email Body ---
            String email = "Unknown Email";
            com.google.firebase.auth.FirebaseUser user = com.google.firebase.auth.FirebaseAuth.getInstance().getCurrentUser();
            if (user != null && user.getEmail() != null) email = user.getEmail();

            String role = AuthManager.getInstance().getCurrentUserRole();
            String dateTime = new SimpleDateFormat("MMM dd, yyyy hh:mm a", Locale.getDefault()).format(new Date());

            String body = "Please find the attached report generated from the Sales Inventory App.\n\n" +
                    "================================\n" +
                    "Generated By: " + email + "\n" +
                    "Role/Access: " + role + "\n" +
                    "Date & Time: " + dateTime + "\n" +
                    "================================\n\n" +
                    "This is an automated message. Please do not reply.";

            emailIntent.putExtra(android.content.Intent.EXTRA_TEXT, body);
            emailIntent.putExtra(android.content.Intent.EXTRA_STREAM, fileUri);

            // --- CRITICAL FIX 2: Gmail Attachment Download Bug Fix (Scoped Storage) ---
            emailIntent.addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION);
            emailIntent.addFlags(android.content.Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.JELLY_BEAN) {
                emailIntent.setClipData(android.content.ClipData.newRawUri("", fileUri));
            }

            android.content.Intent chooser = android.content.Intent.createChooser(emailIntent, "Send Report via...");
            chooser.addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION);
            context.startActivity(chooser);

        } catch (Exception e) {
            Toast.makeText(context, "Error opening email app. Ensure FileProvider is setup.", Toast.LENGTH_SHORT).show();
            e.printStackTrace();
        }
    }
}